language: php

php:
  - 7
  - 7.1

sudo: required

services:
  - mysql

before_script:
  - set -e
  - wget https://packages.couchbase.com/releases/5.0.1/couchbase-server-community_5.0.1-ubuntu14.04_amd64.deb
  - sudo dpkg -i couchbase-release-1.0-2-amd64.deb
  - sudo apt-get update
  - sudo apt-get install libcouchbase-dev
  - cd /opt/couchbase
  - ./bin/couchbase-server -- -noinput -detached
  - sleep 20
  - ./bin/couchbase-cli cluster-init -c 127.0.0.1:8091  --cluster-username=Administrator --cluster-password=password --cluster-port=8091 --cluster-index-ramsize=512 --cluster-ramsize=512 --services=data,query,index
  - ./bin/couchbase-cli bucket-create -c 127.0.0.1:8091 --bucket=testing --bucket-type=couchbase --bucket-port=11211 --bucket-ramsize=512  --bucket-replica=1 -u Administrator -p password
  - sleep 10
  - ./bin/cbq -e http://127.0.0.1:8091 --script "CREATE PRIMARY INDEX ON testing USING GSI;"
  - mysql -e 'create database testing;'
  - pecl install pcs-1.3.1
  - pecl install couchbase-2.2.4
  - cd $TRAVIS_BUILD_DIR
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml
  
before_install:
  - pip install --user codecov

after_success:
  - codecov